### ISSUE TITLE
Error retrieving cluster structure when the cluster dropdown selection was changed

### ISSUE THREAD

**Issue by kashif-khan** [kdcro101/vscode-cassandra#4]
**Describe the bug**
Changing the cluster dropdown value in the CQL editor does not load keyspace dropdown. 

**To Reproduce**
1. Open a CQL editor.
2. Select a cluster from the dropdown and then select a keyspace in its dropdown control.
3. Then change the cluster dropdown and observe the keyspace dropdown showing the error `Error retrieving cluster structure`.

**Expected behavior**
Whenever a cluster dropdown value is changed then its appropriate keyspace dropdown should be populated if the cluster is able to connect to it.

**Screenshots**
![cassandra-workbench-bug-3](https://user-images.githubusercontent.com/661339/48221183-605c9280-e3b7-11e8-8457-75ca9a644c8e.gif)

**System info (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise 64 bit [Version 10.0.16299.611]
 - Cassandra version: 2.2.13
 - vscode version: 1.28.2 (user setup)
    - Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
    - Date: 2018-10-17T00:23:51.859Z
    - Electron: 2.0.9
    - Chrome: 61.0.3163.100
    - Node.js: 8.9.3
    - V8: 6.1.534.41
    - Architecture: x64

**Comment by kdcro101** [comment]
@kashif-khan ,

Can't reproduce behavior you described. 
Tested on windows 10 and linux.
If there is multiple clusters defined in configuration and client is being able to connect, keyspace list gets updated.

Can you check Developer tools for any errors?
Are credentials/hosts valid for cluster you are trying to switch to?

**Comment by kdcro101** [comment]
@kashif-khan ,

Closing this issue since I can't reproduce behaviour.

**Comment by kashif-khan** [comment]
@kdcro101 ,

PFA the screenshot of the console error. I tried four times hence it shows 4 errors of the same type.

![screenshot 214](https://user-images.githubusercontent.com/661339/48556932-55e84e80-e90b-11e8-9dcd-17fc9095316d.png)

**Comment by kdcro101** [comment]
@kashif-khan ,

Thank you for info!

It is warning for missing label "parseInputRespond". I will fix that.

Can you switch clusters? 
Are keyspaces being populated?

**Comment by kdcro101** [comment]
@kashif-khan ,

Please update to `0.3.1`. Warning should be fixed.
Let me know how it went.

**Comment by kashif-khan** [comment]
@kdcro101 , This issue is still reproducible. Although I believe I know the root cause. It may because of the connection timeout  in the `\vscode-cassandra\ngsrc\src\app\services\cluster\cluster.service.ts` which is currently 10 seconds. I believe increasing this to 30 to 60 seconds should resolve this issue.

`this.message.eventMessage.pipe(
            timeout(10000),
            filter((mi) => mi.name === "e2w_getClusterStructResponse"),`

I was unsuccessful to debug your code. Perhaps if you could add steps on how to debug the code in visual studio code I could contribute to this repository and add more features.

**Comment by kdcro101** [comment]
@kashif-khan,

I will republish extension in few days
